networks:
    verivox:
        name: verivox

services:
    nginx_server:
        image: nginx:stable-alpine
        ports:
            - "80:80"
        tty: true
        volumes:
            - .:/var/www/html:delegated
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - php_fpm
        networks:
            - verivox

    php_fpm:
        image: php_fpm
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www/html:delegated
        command: >
            sh -c "composer update && cp .env.example .env && php artisan optimize"
        networks:
            - verivox
