networks:
    verivox:
        name: verivox

services:
    nginx_server:
        image: nginx:stable-alpine
        ports:
            - "80:80"
        tty: true
        volumes:
            - .:/var/www/html:delegated
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - php_fpm
        networks:
            - verivox

    php_fpm:
        image: php:8.2-fpm
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www/html:delegated
        networks:
            - verivox
