version: "3"

networks:
    verivox:
        name: verivox

services:

    php_fpm:
        build:
            dockerfile: ./docker/php/Dockerfile
        ports:
            - "9000:9000"
        tty: true
        working_dir: /var/www/html
        # volumes:
        #     - .:/var/www/html:delegated
        networks:
            - verivox

    nginx_server:
        image: nginx:stable-alpine
        ports:
            - "80:80"
        tty: true
        volumes:
            - .:/var/www/html:delegated
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - php_fpm
        networks:
            - verivox